log:
  level: info
  file: "/etc/mosdns/mosdns.log"
  # /etc/init.d/mosdns reload
api:
  http: ":9091" # 在该地址启动 api 接口。
  
include:

plugins:
  - tag: "hosts"
    type: "hosts"
    args:
      files:
        - "/etc/mosdns/rule/hosts.txt"
        - "/etc/mosdns/rule/hosts_fastly.txt"
        - "/etc/mosdns/rule/hosts_akamai.txt"
        
  - tag: geosite_cn # 国内域名
    type: domain_set
    args:
      files:
        - "/etc/mosdns/rule/china_domain_list.txt"
        - "/etc/mosdns/rule/apple_cn.txt"   # apple国内CDN
        - "/etc/mosdns/rule/akamai_domain_list.txt" # 主要用于子域名qname 举例: akamaized.net不通
                                                    #             v16m-default.akamaized.net正常
  - tag: "cache_0"
    type: "cache"
    args:
      size: 1024  # 默认: 1024。
      lazy_cache_ttl: 259200  # 默认: 0（禁用 lazy cache）。#建议值 86400（1天）~ 259200（3天）                     
      dump_file: ./cache.dump
      dump_interval: 7200  # (实验性) 自动保存间隔。

  - tag: "forward_local"
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "211.138.180.2" # 运营商 DNS，自行修改
        - addr: "211.138.180.3" # 运营商 DNS，自行修改

  - tag: "forward_open"
    type: forward
    args:
      concurrent: 2
      upstreams:
        - addr: "https://223.5.5.5/dns-query"
          enable_http3: true
        - addr: "https://1.12.12.12/dns-query" #ECS

  - tag: "forward_remote"
    type: "forward"
    args:
      concurrent: 3 # 并发数。每次请求随机选取 concurrent 个 upstreams 发送请求。
                    # 取最快返回的应答。超过 3 最多选 3 个。默认 1。
      upstreams:
        - addr: "https://162.159.36.1/dns-query"
          enable_http3: true
        - addr: "https://doh.opendns.com/dns-query" #ECS：不完全支持
          dial_addr: "146.112.41.2"
        - tag: quad9_ECS
          addr: "https://dns11.quad9.net/dns-query"
          dial_addr: "9.9.9.11"
        - tag: googleDOH_ECS
          addr: "https://dns.google/dns-query"
          dial_addr: "8.8.4.4"
          enable_http3: true
          
  - tag: "forward_easy"
    type: "forward"
    args:
      concurrent: 3
      upstreams:
#        - tag: cooluc_ECS
#          addr: "https://dns.cooluc.com/dns-query"
#          bootstrap: "211.138.180.2"
#          enable_http3: true
        - tag: googleTLS_ECS
          addr: "tls://8.8.4.4"
          enable_pipeline: true
        - addr: "tls://101.101.101.101" #台湾DNS
          enable_pipeline: true
        - addr: "https://doh.apad.pro/dns-query" #ECS优化
          bootstrap: "211.138.180.2"
          
  - tag: has_resp_sequence
    type: sequence
    args:
      - matches:
          - has_resp
        exec: accept

  - tag: remote_sequence # forward 二选一
    type: sequence
    args:
      - exec: prefer_ipv4
#      - exec: forward 127.0.0.1:7874  # mosdns前置：Dnsmasq → mosdns → clash
      - exec: $forward_remote         # mosdns后置：Dnsmasq → clash → mosdns
      - exec: accept
 
  - tag: remote_sequence_tw # 使用 TW ECS 查询优化 国外域名
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: ecs 168.95.0.0
      - exec: $forward_easy
      - exec: return

  - tag: remote_sequence_us # 使用 US ECS 再次查询优化 Fastly CDN 结果
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: ecs 38.94.109.0
      - exec: $forward_remote googleDOH_ECS quad9_ECS
      - exec: jump has_resp_sequence

  # IP 优选，需要定期修改，最好填写 2 - 4 个
  - tag: blackhole_akamai # 替换部分 AKAMAI 域名 IP，详见 https://github.com/IrineSistiana/mosdns/discussions/489
    type: sequence
    args:
      - exec: black_hole 184.26.91.172 23.48.201.25 23.202.34.68
      - exec: query_summary best_akamai
      - exec: ttl 3600-0
      - exec: accept # 运行 black_hole 之后接受请求，不再进行后续判断
      
  - tag: blackhole_cloudflare
    type: sequence
    args:
      - exec: black_hole 104.19.150.57 104.16.153.177 104.17.118.97
      - exec: query_summary cloudflare_best
      - exec: ttl 3600-0
      - exec: accept

  - tag: blackhole_cloudfront
    type: sequence
    args:
      - exec: black_hole 108.139.4.72 13.227.74.215 13.249.160.37
      - exec: query_summary cloudfront_best
      - exec: ttl 3600-0
      - exec: accept

  - tag: change_cdn_ip # https://github.com/XIU2/CloudflareSpeedTest/discussions/317
    type: sequence
    args:
      - matches: # akamai.net 优选ip
          - cname akamai.net
          - qtype 1
          - has_wanted_ans # 防止纯 IPV6 域名被替换
        exec: jump blackhole_akamai

      - matches: # 有些 AKAMAI 的域名不能直接替换 IP（没有绑定全证书）
          - cname &./rule/akamai_domain_list.txt 
        exec: accept # 此处多加一次判断，接受全部 AKAMAI CDN 的 域名 防止再请求一次dns

      - matches: # cloudflare 优选ip
          - qtype 1
          - has_wanted_ans
          - "resp_ip &./rule/cloudflare-ipv4.txt"
        exec: jump blackhole_cloudflare
        
      - matches: # cloudfront 优选ip
          - qtype 1
          - has_wanted_ans
          - "resp_ip &./rule/cloudfront.txt"
        exec: jump blackhole_cloudfront
      - exec: return
      
  - tag: reforward_fastly_remote
    type: sequence
    args:
      - matches:
          - "resp_ip &./rule/fastly.txt"
        exec: jump remote_sequence_us
      - exec: return
      
  - tag: gfw_ip_sequence
    type: sequence
    args:
      - matches: # 污染ip
          - "resp_ip &./rule/gfw_ip_list.txt" 
        exec: goto remote_sequence
      - exec: return

  - tag: open_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_open
      - exec: jump gfw_ip_sequence
      - exec: jump reforward_fastly_remote
      - exec: jump change_cdn_ip
      - exec: accept # 有没有响应都终止，防止后续查询其他上游

  - tag: default_sequence
    type: sequence
    args:
      - exec: prefer_ipv4
      - exec: $forward_open # 默认用国内，用来查询是否污染
      - exec: jump gfw_ip_sequence
      - matches:
          - "resp_ip &./rule/china_ip_list.txt"
        exec: accept # 国内直接接受
      - exec: drop_resp

  - tag: Global_sequence
    type: sequence
    args:
      - exec: jump remote_sequence_tw       # mosdns前置：走 TW ECS 直连，删去 _tw 代表国外全部走代理
      - exec: jump reforward_fastly_remote  # mosdns后置：可以删去 _tw 不删也可。MATCH若走直连，建议不删
      - exec: jump change_cdn_ip
      - exec: jump has_resp_sequence

  - tag: "fallback"
    type: "fallback"
    args:
      primary: default_sequence    # 国内ip走直连，如果是gfw ip 走代理
      secondary: Global_sequence   # 国外ip 尝试优选  走直连
      threshold: 360           # 无响应回滚阈值。单位毫秒。默认 500 。
      always_standby: true     # 副可执行插件始终待命。
       
  - tag: main
    type: sequence
    args:
      - matches:
          - qtype 65
        exec: reject 3 # 屏蔽 QTYPE 65

      - exec: $hosts
      - exec: jump has_resp_sequence

      - matches:
          - qname &./rule/private.txt &./rule/block_list.txt #内网域名 & 黑名单
        exec: reject 5 # 屏蔽内网域名

      - matches:
          - qname &./rule/white_list.txt # DDNS 和 其他白名单
        exec: $forward_local # 运营商DNS
#      - exec: ttl 5-180
      - exec: jump has_resp_sequence

      - exec: $cache_0 # 下面的请求结果均进入缓存

      - matches:
          - qname &./rule/google_cn.txt &./rule/wall_list.txt # wall_list手动创建
        exec: jump remote_sequence # 适用于被墙/被污染/尚未移出geosite_cn列表的，提前走代理

      - matches:
          - qname $geosite_cn
        exec: jump open_sequence # 国内域名 & apple cn & 令存在于gfwlist列表中的部分国内cdn，提前走直连
        
      - matches:
          - qname &./rule/proxy_domain_list.txt # GFW 域名直接请求clash
        exec: jump remote_sequence
        
      - exec: $fallback
      
  - tag: udp_server
    type: udp_server
    args:
      entry: main
      listen: ":5335"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main
      listen: ":5335"
