log:
  level: info
  file: "./mosdns.log"
  # /etc/init.d/mosdns reload

api:
  http: ":9091" # 在该地址启动 api 接口。 
include:
  - "./forward.yaml"
  - "./load_rules.yaml"
  - "./blackhole.yaml"

plugins:

  - tag: "cache_0"
    type: "cache"
    args:
      size: 8192  # 默认: 1024。
      lazy_cache_ttl: 259200  # 默认: 0（禁用 lazy cache）。#建议值 86400（1天）~ 259200（3天）
      dump_file: ./cache_0.dump 
      dump_interval: 7200  # (实验性) 自动保存间隔。

  - tag: has_resp_sequence
    type: sequence
    args:
      - matches:
          - has_resp
        exec: accept

  - tag: remote_sequence # forward 二选一
    type: sequence
    args:
#      - exec: $forward_fakeip           # mosdns前置：Dnsmasq → mosdns → clash
#      - exec: ttl 1
      - exec: $forward_remote           # mosdns后置：Dnsmasq → clash → mosdns
      - exec: accept

  - tag: gfw_ip_sequence
    type: sequence
    args:
      - matches: # 污染ip 屏蔽ip
          - "resp_ip $banned_ip 0.0.0.0 127.0.0.1 ::1"
        exec: debug_print dns_hijack # 打印日志 后期放入wall_list.txt
      - matches: # 污染ip 屏蔽ip
          - "resp_ip $banned_ip 0.0.0.0 127.0.0.1 ::1"
        exec: jump remote_sequence
    
  - tag: local_sequence
    type: sequence
    args:
      - exec: $forward_local # 这里推荐使用当地运营商dns
      - exec: jump gfw_ip_sequence
      - exec: jump change_cdn_ip
      - exec: jump change_cdn_akamai
      - exec: accept # 有没有响应都终止，防止后续查询其他上游

  - tag: gfw_akamai_sequence
    type: sequence
    args:
      - exec: $forward_remote
      - exec: jump change_cdn_akamai
#      - exec: $forward_fakeip
#      - exec: ttl 1
      - exec: accept
      
  - tag: ali_sequence_jp # 阿里日本准确度高，腾讯美国准确度高
    type: sequence
    args:
      - exec: $ecs_jp
      - exec: $forward_alidns ali_doh 
      - exec: jump change_cdn_ip
      - exec: jump change_cdn_akamai
      - exec: accept

  - tag: tencent_sequence_lax
    type: sequence
    args:
      - exec: $ecs_lax
      - exec: $forward_dnspod
      - exec: jump change_cdn_ip
      - exec: jump change_cdn_akamai
      - exec: accept

  - tag: default_sequence
    type: sequence
    args:
      - exec: $forward_alidns # 默认用国内，用来查询是否污染
      - exec: jump gfw_ip_sequence
      - exec: jump change_cdn_ip
      - exec: jump change_cdn_akamai
      - matches:
          - "!resp_ip $geoip_cn"
        exec: drop_resp # 国内直接接受
      
  - tag: "fallback_final"
    type: "fallback"
    args:
      primary: default_sequence       # 国内ip走直连，如果是gfw ip 走代理
      secondary: remote_sequence   # 国外ip 尝试优选  走直连
      threshold: 360           # 无响应回滚阈值。单位毫秒。默认 500 。
      always_standby: true     # 副可执行插件始终待命。
      
  - tag: main
    type: sequence
    args:
      - matches:
          - qtype 65
        exec: reject 3 # 屏蔽 QTYPE 65

      - matches:
          - qname $greylist &./rule/wall_list.txt &./rule/dns_hijack.txt  # wall_list.txt手动创建手动更新 dns_hijack.txt手动创建脚本自动更新
        exec: jump remote_sequence # 适用于被墙/被污染/尚未移出geosite_cn列表的，提前走代理

      - exec: $redirect
      
      - exec: $hosts
      - exec: jump has_resp_sequence
      - exec: $hosts_fastly
      - exec: jump has_resp_sequence
      - exec: $hosts_akamai
      - exec: jump has_resp_sequence
      
      - matches:
          - qname $privatelist $blocklist #内网域名 & 黑名单
        exec: reject 5

      - matches:
          - qname $whitelist # DDNS 和 白名单
        exec: $forward_local
#      - exec: ttl 5-180 #如果使用了DDNS，把这个打开
      - exec: jump has_resp_sequence

      - matches: "!qtype 1 28"
        exec: $forward_remote doh_ecs_cloudflare
      - matches: "!qtype 1 28" # = accept
        exec: accept

      - exec: $cache_0
      - exec: jump has_resp_sequence

      - matches:
          - qname $akamailist
        exec: jump ali_sequence_jp

      - matches:
          - qname ebay.com # 占位
        exec: jump tencent_sequence_lax

      - matches:
          - qname apple.com edgesuite.net icloud.com live.com live.net msftconnecttest.com office365.com office.com outlook.com trafficmanager.net xbox.com
        exec: $forward_dnspod
      - exec: jump has_resp_sequence

      - matches:
          - qname $originallist # 不进行 IP 替换的域名，通常是游戏等使用非常用端口的域名
        exec: $forward_remote
      - exec: jump has_resp_sequence

      - matches:
          - qname $google_cn
        exec: jump remote_sequence # 适用于被墙/被污染/尚未移出geosite_cn列表的，提前走代理

      - matches:
          - qname $geosite_cn
        exec: jump local_sequence # 国内域名 & apple cn & Microsoft_cn 提前走直连

      - matches:
          - qname $gfwlist # GFW 域名直接走代理
        exec: jump gfw_akamai_sequence

      - exec: $fallback_final # 不在列表内的域名

  - tag: udp_server
    type: udp_server
    args:
      entry: main
      listen: ":5353"

  - tag: tcp_server
    type: tcp_server
    args:
      entry: main
      listen: ":5353"

 # UDP DNS劫持
#  - tag: udp_hijack
#    type: udp_server
#    args:
#      entry: main
#      listen: ":5335"